# Generated by Django 3.0.8 on 2020-09-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='trans',
            field=models.BooleanField(default=False),
        ),
    ]
