# Generated by Django 3.0.8 on 2020-09-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_members_trans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='trans',
        ),
    ]
