# Generated by Django 3.0.8 on 2020-09-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_members_trans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('rname', models.CharField(max_length=100)),
                ('tcredit', models.IntegerField()),
            ],
        ),
    ]
