# Generated by Django 3.0.8 on 2020-09-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_tran'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tran',
            old_name='tcredit',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='tran',
            old_name='rname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tran',
            name='sname',
        ),
    ]
